name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Enable corepack and install
        run: |
          corepack enable
          yarn install

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test:run

      - name: Build
        run: |
          NODE_ENV=production yarn build

      - name: GH Pages deploy
        uses: Cecilapp/GitHub-Pages-deploy@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          email: robot@golebiowski.me
          build_dir: out
          branch: gh-pages
          commit_message: Deploy the app
